module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        'primary-hover': 'var(--primary-hover)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart1: 'var(--chart-1)',
        chart2: 'var(--chart-2)',
        chart3: 'var(--chart-3)',
        chart4: 'var(--chart-4)',
        chart5: 'var(--chart-5)',
      },
    },
  },
  plugins: [
    require('tailwindcss/plugin')(function ({ addBase }) {
      addBase({
        ':root': {
          '--background': '#ffffff',
          '--foreground': '#0d0d0d',
          '--card': '#ffffff',
          '--card-foreground': '#0d0d0d',
          '--popover': '#ffffff',
          '--popover-foreground': '#0d0d0d',
          '--primary': '#rgba(20, 130, 212, 1)',
          '--primary-hover': 'rgba(20, 130, 212, 1)',
          '--primary-foreground': '#f0f8ff',
          '--secondary': '#e3f2fd',
          '--secondary-foreground': '#1a1a1a',
          '--muted': '#f5f5f5',
          '--muted-foreground': '#757575',
          '--accent': '#e3f2fd',
          '--accent-foreground': '#1a1a1a',
          '--destructive': '#e53935',
          '--destructive-foreground': '#ffffff',
          '--border': '#d3d3d3',
          '--input': '#d3d3d3',
          '--ring': '#377bb5',
          '--chart-1': '#e57373',
          '--chart-2': '#64b5f6',
          '--chart-3': '#4db6ac',
          '--chart-4': '#fff176',
          '--chart-5': '#aed581',
        },
        '.dark': {
          '--background': '#1e1e1e',
          '--foreground': '#f5f5f5',
          '--card': '#2a2a2a',
          '--card-foreground': '#f5f5f5',
          '--popover': '#2a2a2a',
          '--popover-foreground': '#f5f5f5',
          '--primary': '#377bb5',
          '--primary-hover': 'rgba(74, 144, 226, 0.9)',
          '--primary-foreground': '#1a1a1a',
          '--secondary': '#2c3e50',
          '--secondary-foreground': '#f5f5f5',
          '--muted': '#3c3c3c',
          '--muted-foreground': '#9e9e9e',
          '--accent': '#4a90e2',
          '--accent-foreground': '#f5f5f5',
          '--destructive': '#d32f2f',
          '--destructive-foreground': '#f5f5f5',
          '--border': '#424242',
          '--input': '#424242',
          '--ring': '#4a90e2',
          '--chart-1': '#e57373',
          '--chart-2': '#64b5f6',
          '--chart-3': '#4db6ac',
          '--chart-4': '#fff176',
          '--chart-5': '#aed581',
        },
      });
    }),
  ],
  darkMode: ['class'], // Ensures dark mode works with class-based toggle
};
